### ISSUE TITLE
simulator not working with Unity 2018.2.4f1

### ISSUE THREAD

**Issue by Francisobiagwu** [lgsvl/simulator#247]
I cloned the simulator repo as directed in git. I equally downloaded the old version of unity, 2018.2.4f1. However, the scenes don't open, instead I get a lot of compilation errors as shown in the screenshot attached. Please, doesn't anyone know what is responsible for this problem?

<img width="1440" alt="Screen Shot 2019-07-23 at 9 10 05 AM" src="https://user-images.githubusercontent.com/19335305/61714973-125fa300-ad2a-11e9-9d66-92af69d3878b.png">
<img width="1440" alt="Screen Shot 2019-07-23 at 9 09 30 AM" src="https://user-images.githubusercontent.com/19335305/61715000-23a8af80-ad2a-11e9-9025-787faebbcfb2.png">

**Comment by martins-mozeiko** [comment]
Please check that you have correctly installed [Git LFS](https://git-lfs.github.com/) before you clone repository. We use git lfs file storage to make cloning faster - as it will download files only needed in current commit, not whole history.

**Comment by Francisobiagwu** [comment]
thanks.
Fixed.
